name: cryptozombies

plugins:
  - name: solidity
  - name: hardhat

solidity:
  version: 0.4.26

compilers:
  solidity:
    versions:
      - 0.4.26
      - 0.8.31

contracts_folder: contracts

test:
  folder: tests

networks:
  ethereum:
    local:
      default_provider: hardhat